apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 1-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 1-java-quarkus
    app.kubernetes.io/part-of: test-app1652437191-271
  name: 1-java-quarkus
  namespace: kkanova
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: 1-java-quarkus
status:
  loadBalancer: {}
